### ISSUE TITLE
problem with some not deallocated pointers

### ISSUE THREAD

**Issue by CyrilleBonamy** [sdsc/p3dfft#9]
Hi

When i run two instances of p3dfft, i have some problems with pointers not deallocated.
I have fixed this issue : i have add two dealocate :

diff --git a/build/module.F90 b/build/module.F90
index f2d150a..cdaa2da 100644
--- a/build/module.F90
+++ b/build/module.F90
@@ -297,6 +297,7 @@
       enddo
 
       deallocate(plan1_frc,plan1_bcr,plan1_fc,plan2_fc_same,plan1_bc,plan2_bc_same,plan_ctrans_same,plan_strans_same)
+      deallocate(plan_ctrans_dif,plan_strans_dif,plan2_fc_dif,plan2_bc_dif)
 #ifdef STRIDE1
       deallocate(plan_ctrans_dif,plan_strans_dif,plan2_fc_dif,plan2_bc_dif)
 #endif

**Comment by dmitrypek** [comment]
Done.
